[project]
name = "lunchcr"
version = "0.1.0"
description = "lunchmoney for CR banking."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lunchable>=1.4.3",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
    "ty>=0.0.1a23",
]
